server:
  port: 8003
spring:
  application:
    name: zuul-server
eureka:
  client:
    service-url:
      defaultZone: http://peer2:8762/eureka/, http://peer1:8761/eureka/
zuul:
  routes:
    service1:
      path: /service1/**
      serviceId: user-client

